version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "djkotowski"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "djkotowski"
    schedule:
      interval: "daily"
